KimBab1234/itwill_team1_danggle

Test_git_itwill/src/board/KNY.java
=> KNY 1ST COMMIT

Test_git_itwill/src/board/jjs.java
=> commit 합니다

Team1_DaengGeul/src/main/webapp/review/review_list.jsp
=> 1.3 review_list 다시 수정(남영)

Team1_DaengGeul/src/main/java/action/ReviewLikeUpdateAction.java, Team1_DaengGeul/src/main/java/dao/ReviewDAO.java, Team1_DaengGeul/src/main/java/svc/ReviewLikeUpdateService.java, Team1_DaengGeul/src/main/java/svc/ReviewListService.java, Team1_DaengGeul/src/main/webapp/review/review_view.jsp
=> 1.4 review_view.jsp(+관련파일) 좋아요 수정 (남영)

Team1_DaengGeul/src/main/java/dao/ReviewDAO.java, Team1_DaengGeul/src/main/webapp/review/review_view.jsp
=> 1.4 리뷰 수정 (남영)

Team1_DaengGeul/src/main/webapp/inc/main.jsp, Team1_DaengGeul/src/main/webapp/inc/main_index.jsp, Team1_DaengGeul/src/main/webapp/product/productList.jsp
추천 도서 선택 안했을 때 alert창 추가, 추천 도서 목록 링크 연결했습니다!
=> 220105 김경민 추천 도서 선택 안하고 등록 시 alert창 추가, 추천 도서 목록 링크 연결

Team1_DaengGeul/src/main/java/action/CommunityDeleteAction.java, Team1_DaengGeul/src/main/java/action/CommunityDetailAction.java, Team1_DaengGeul/src/main/java/action/CommunityListAction.java, Team1_DaengGeul/src/main/java/action/CommunityReplyAction.java, Team1_DaengGeul/src/main/java/action/CommunityWriteAction.java, Team1_DaengGeul/src/main/java/controller/CommunityFrontController.java, Team1_DaengGeul/src/main/java/dao/CommunityDAO.java, Team1_DaengGeul/src/main/java/svc/CommunityDetailService.java, Team1_DaengGeul/src/main/java/svc/CommunityListService.java, Team1_DaengGeul/src/main/java/svc/CommunityReplyListService.java, Team1_DaengGeul/src/main/java/svc/CommunityReplyWriteService.java, Team1_DaengGeul/src/main/java/svc/CommunityWriteService.java, Team1_DaengGeul/src/main/java/vo/CommunityBean.java, Team1_DaengGeul/src/main/java/vo/Reply.java, Team1_DaengGeul/src/main/webapp/community/CommunityDetail.jsp, Team1_DaengGeul/src/main/webapp/community/CommunityWriteForm0.jsp, Team1_DaengGeul/src/main/webapp/community/CommunityWriteForm1.jsp, Team1_DaengGeul/src/main/webapp/community/Community_List0.jsp, Team1_DaengGeul/src/main/webapp/community/Community_List1.jsp
=> jjs / 1-6 / 커뮤니티추가

Team1_DaengGeul/src/main/webapp/product/productList.jsp
페이지 버튼 수정했습니다!
다음 페이지로 잘 넘어가요!
=> 220105 김경민 페이지 버튼 수정

Team1_DaengGeul/src/main/webapp/review/css/review_modify.css, Team1_DaengGeul/src/main/webapp/review/css/review_view.css, Team1_DaengGeul/src/main/webapp/review/review_modify.jsp, Team1_DaengGeul/src/main/webapp/review/review_view.jsp, Team1_DaengGeul/src/main/webapp/review/review_write.jsp
1.6 리뷰 별점 수정(남영) - 모양 추후 수정 예정
=> 1.6 리뷰 별점 수정(남영) - 모양 추후 수정 예정

Team1_DaengGeul/src/main/java/action/RecommendBookAction.java, Team1_DaengGeul/src/main/java/dao/ProductDAO.java, Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp
추천 도서 등록 시 confirm으로 페이지 이동 하는 기능과 상품 등록 페이지에 required 속성 추가 했습니다!^0^
=> 220106 추천 도서 등록시 confirm으로 페이지 이동 추가, 상품 등록 페이지 required 속성 추가

Team1_DaengGeul/src/main/webapp/review/review_modify.jsp, Team1_DaengGeul/src/main/webapp/review/review_view.jsp, Team1_DaengGeul/src/main/webapp/review/review_write.jsp
=> 1.6 별점 모양 수정(남영)

Team1_DaengGeul/src/main/java/action/MemberInfoAction.java, Team1_DaengGeul/src/main/java/action/MemberUpdateProAction.java, Team1_DaengGeul/src/main/webapp/css/MemberInfoForm.css, Team1_DaengGeul/src/main/webapp/member/member_info.jsp
View 페이지 갱신했고 각자 담당하는 파트 최신글 뿌려주세요..
action은 휴대전화번호 분할작업 때문에 다시 올렸어!
=> 회원정보 View 페이지 갱신

Team1_DaengGeul/src/main/webapp/community/CommunityDetail.jsp, Team1_DaengGeul/src/main/webapp/community/Community_List0.jsp, Team1_DaengGeul/src/main/webapp/community/Community_List1.jsp, Team1_DaengGeul/src/main/webapp/inc/main.jsp, Team1_DaengGeul/src/main/webapp/inc/main_index.jsp
=> 23.01.08 main, main_index hover=>click로 고침, community 주소 일부 .cu=>.co로 고침

Team1_DaengGeul/src/main/java/action/MemberDeleteProAction.java, Team1_DaengGeul/src/main/java/action/MemberInfoAction.java, Team1_DaengGeul/src/main/java/action/MemberUpdateProAction.java, Team1_DaengGeul/src/main/java/dao/MemberDAO.java, Team1_DaengGeul/src/main/webapp/css/memberInfoSearchForm.css, Team1_DaengGeul/src/main/webapp/css/memberList.css, Team1_DaengGeul/src/main/webapp/member/member_delete_result.jsp, Team1_DaengGeul/src/main/webapp/member/member_info.jsp, Team1_DaengGeul/src/main/webapp/member/member_info_search_form.jsp, Team1_DaengGeul/src/main/webapp/member/member_join_form.jsp, Team1_DaengGeul/src/main/webapp/member/member_join_result.jsp, Team1_DaengGeul/src/main/webapp/member/member_list.jsp, Team1_DaengGeul/src/main/webapp/member/member_search_passwd_result.jsp
=> 마이페이지 관련 작업

Team1_DaengGeul/src/main/java/action/ReviewDetailAction.java, Team1_DaengGeul/src/main/java/action/ReviewModifyFormAction.java, Team1_DaengGeul/src/main/java/action/ReviewWriteFormAction.java, Team1_DaengGeul/src/main/java/action/ReviewWriteProAction.java, Team1_DaengGeul/src/main/java/controller/ReviewFrontController.java, Team1_DaengGeul/src/main/java/dao/ReviewDAO.java, Team1_DaengGeul/src/main/java/svc/ReviewWriteFormService.java, Team1_DaengGeul/src/main/java/vo/ReviewBean.java, Team1_DaengGeul/src/main/webapp/review/review_list.jsp, Team1_DaengGeul/src/main/webapp/review/review_modify.jsp, Team1_DaengGeul/src/main/webapp/review/review_view.jsp, Team1_DaengGeul/src/main/webapp/review/review_write.jsp
=> 1.9 리뷰 상품 이미지 및 이름 수정(남영)

Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp
상품 등록 페이지에 책 카테고리에 required 넣는 거 깜빡해서 추가했어요!
=> 230109 김경민 상품 등록 페이지 책 카테고리 required 속성 추가

Team1_DaengGeul/src/main/webapp/member/member_info.jsp, Team1_DaengGeul/src/main/webapp/member/member_join_form.jsp
=> 회원가입, 마이페이지 유효성검사 오류 수정

Team1_DaengGeul/src/main/java/action/ReviewDetailAction.java, Team1_DaengGeul/src/main/java/dao/ReviewDAO.java, Team1_DaengGeul/src/main/java/svc/ReviewDetailService.java, Team1_DaengGeul/src/main/webapp/review/review_list.jsp
=> 1.10 리뷰 목록 수정(남영)

Team1_DaengGeul/src/main/webapp/css/MemberInfoForm.css, Team1_DaengGeul/src/main/webapp/member/member_info.jsp
=> 마이페이지 양식 수정(급한거X)

Team1_DaengGeul/src/main/webapp/community/CommunityDetail.jsp, Team1_DaengGeul/src/main/webapp/community/Community_List0.jsp, Team1_DaengGeul/src/main/webapp/community/Community_List1.jsp, Team1_DaengGeul/src/main/webapp/inc/community_left.jsp
=> css / jjs / 0110

Team1_DaengGeul/src/main/webapp/css/product.css, Team1_DaengGeul/src/main/webapp/product/productList.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_detail.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_form.jsp, Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp, Team1_DaengGeul/src/main/webapp/product/recommend_bookList.jsp
=> 230110 김경민 css 수정, 제이쿼리...? 추가

Team1_DaengGeul/src/main/webapp/review/review_delete.jsp, Team1_DaengGeul/src/main/webapp/review/review_list.jsp, Team1_DaengGeul/src/main/webapp/review/review_modify.jsp, Team1_DaengGeul/src/main/webapp/review/review_view.jsp, Team1_DaengGeul/src/main/webapp/review/review_write.jsp
=> 1.10 리뷰 css (남영)

Team1_DaengGeul/src/main/webapp/review/review_delete.jsp, Team1_DaengGeul/src/main/webapp/review/review_modify.jsp, Team1_DaengGeul/src/main/webapp/review/review_view.jsp
=> 1.11 리뷰 수정(남영)

Team1_DaengGeul/src/main/java/dao/ProductDAO.java, Team1_DaengGeul/src/main/webapp/css/product.css, Team1_DaengGeul/src/main/webapp/product/productList.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_form.jsp, Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp
=> 230111 김경민 테스트케이스 후 수정 완료!

Team1_DaengGeul/src/main/webapp/review/review_list.jsp
=> 1.11 리뷰 목록 이름 수정 (남영)

Team1_DaengGeul/src/main/webapp/css/product.css
=> 커서 추가했어요~!!

Team1_DaengGeul/src/main/webapp/member/member_join_form.jsp
=> 경민아 미안해.. 수정했어 ㅋㅋㅋ

Team1_DaengGeul/src/main/webapp/css/product.css
=> 왜인지 모를 css 추가 있어요..

Team1_DaengGeul/src/main/java/dao/ReviewDAO.java
=> 1.11 정렬 수정 (남영)

Team1_DaengGeul/src/main/webapp/css/product.css, Team1_DaengGeul/src/main/webapp/inc/main.jsp, Team1_DaengGeul/src/main/webapp/inc/main_index.jsp, Team1_DaengGeul/src/main/webapp/inc/memberInfo_left.jsp, Team1_DaengGeul/src/main/webapp/product/productList.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_detail.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_form.jsp, Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp, Team1_DaengGeul/src/main/webapp/product/recommend_bookList.jsp
=> 230112 김경민 css left 추가 회원 관리 목록 추가

Team1_DaengGeul/src/main/webapp/inc/memberInfo_left.jsp
=> 230112 김경민 css 하나 더 수정했어요...ㅎㅎ

Team1_DaengGeul/src/main/webapp/review/review_list.jsp, Team1_DaengGeul/src/main/webapp/review/review_write.jsp
=> 1.12 리뷰 별점 수정(남영)

Team1_DaengGeul/src/main/webapp/product/product_edit_form.jsp, Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp
=> 230112 fakepath 수정 완료~!

Team1_DaengGeul/src/main/java/action/ProductDeleteAction.java, Team1_DaengGeul/src/main/webapp/product/productList.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_detail.jsp, Team1_DaengGeul/src/main/webapp/product/product_edit_form.jsp, Team1_DaengGeul/src/main/webapp/product/product_registration_form.jsp, Team1_DaengGeul/src/main/webapp/product/recommend_bookList.jsp
=> 230112 김경민 상품 삭제 전 alert 창 추가!

Team1_DaengGeul/src/main/webapp/product/productList.jsp
=> 품절 처리 했습니다~

Team1_DaengGeul/src/main/webapp/member/member_delete.jsp, Team1_DaengGeul/src/main/webapp/member/member_info.jsp
=> 마이페이지 코드수정

Team1_DaengGeul/build/classes/.gitignore
=> 1.17 남영 gitignore

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/ItemController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/Item.java, Team1_Final/src/main/webapp/WEB-INF/views/inc/left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/item/item_regist.jsp
=> 1.27 품목 진짜 조금 ㅎ(남영)

Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/controller/BookFrontController.java, Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/mapper/ProductMapper.java, Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/svc/ProductService.java, Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/vo/ProductBean.java, Team1_DaengGeul_Spring/src/main/resources/com/itwillbs/team1/mapper/ProductMapper.xml, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/product/product_registration_form.jsp
=> 230127 책 등록 가능!

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/ItemController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/ItemVO.java, Team1_Final/src/main/webapp/WEB-INF/views/item/item_regist.jsp
=> 1.29 남영 품목 항목

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/ItemController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/ItemMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/ItemService.java, Team1_Final/src/main/webapp/WEB-INF/views/inc/left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/item/item_regist.jsp
=> 1.30 남영 품목 & 조회창

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/ItemController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/ItemMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/ItemService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/ItemVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/ItemMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/inc/left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/item/item_inquiry.jsp, Team1_Final/src/main/webapp/WEB-INF/views/item/item_regist.jsp
=> 1.30 남영(품목 등록, 조회)

Team1_Final/src/main/webapp/WEB-INF/views/inc/pd_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/top.jsp, Team1_Final/src/main/webapp/WEB-INF/views/pd/pd_inquiry.jsp, Team1_Final/src/main/webapp/WEB-INF/views/pd/pd_regist.jsp
=> 23.02.01 남영 탭 다시 만들었어요

Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/controller/BookFrontController.java, Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/mapper/ProductMapper.java, Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/svc/ProductService.java, Team1_DaengGeul_Spring/src/main/resources/com/itwillbs/team1/mapper/ProductMapper.xml, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/fail_back.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/product/productList.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/product/product_edit_form.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/product/recommend_bookList.jsp
=> 230202 댕글댕글 프로젝트

Team1_Final/src/main/webapp/resources/css/in.css
=> 230202 입고 css 추가

Team1_Final/src/main/java/com/itwillbs/team1_final/vo/InVO.java, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_schedule_list.jsp, Team1_Final/src/main/webapp/resources/css/in.css
=> 230202 입고예정 폼 모양만 완성,,,

Team1_Final/src/main/webapp/WEB-INF/views/inc/acc_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/hr_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/in_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/pd_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/purchase_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/regist_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/request_left.jsp, Team1_Final/src/main/webapp/WEB-INF/views/inc/wms_left.jsp
=> left CSS 수정 - 네비바 고정

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/InController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/InMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/InService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/InVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/search_employee.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/search_product.jsp, Team1_Final/src/main/webapp/resources/css/in.css
=> 230203 사원 조회, 품목 조회 가능

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/OutService.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/out/out_accSearch.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_process_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_schedule_list.jsp, Team1_Final/src/main/webapp/resources/css/out.css
=> 창고예정 - 거래처 검색 기능

Team1_Final/src/main/webapp/WEB-INF/views/in/in_schedule_list.jsp, Team1_Final/src/main/webapp/resources/css/in.css
=> 230202 입고예정 페이지  css 수정했어요~~!

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/AccController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/AccMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/AccService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/AccVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/AccMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_delete.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_detail.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_modify.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_regist.jsp
=> 추가하는중.. // 지수

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/OutPdVO.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/OutSchVo.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_schedule_list.jsp, Team1_Final/src/main/webapp/resources/css/out.css
=> 출고 오류덩어리..

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/OutService.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp
=> 출고예정, 출고예정품목 등록 완료

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/InController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/InMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/InService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/InPdVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_process_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_update.jsp
=> 230207 상품 상세내용 조회 가능

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/OutService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/OutSchVo.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/out/out_schedule_list.jsp
=> 출고 ㅁ..ㅗㄱ..로ㄱ..

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/OutService.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/out/out_schedule_list.jsp
=> ddsadfmal;kdfnsdflknsdglkjasn

Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml
List<OutPdVO> outSchPd = mapper.selectOutSchPd(sOut_schesule_cd);
for(int j = 0; j < outSchPd.size(); j++) {
int sProduct_cd = outSchPd.get(j).getPRODUCT_CD();
List<PdVO> pdInfo = mapper.selectPdInfo(sProduct_cd);
outSch.get(i).setPRODUCT_NAME(pdInfo.get(i).getPRODUCT_NAME());
outSch.get(i).setSIZE_DES(pdInfo.get(i).getSIZE_DES());
}
=> String sOut_schesule_cd = outSch.get(i).getOUT_SCHEDULE_CD();

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/InController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/InMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/InService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/InPdVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/search_stock_cd.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/search_wh.jsp, Team1_Final/src/main/webapp/resources/css/in.css
=> 230208 창고 검색, 재고 번호 검색 가능

Team1_Final/src/main/java/com/itwillbs/team1_final/vo/StockVO.java
=> 230208 vo 추가!

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/InController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/InMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/StockVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp
=> stockVo에 하나 더 추가했어요

Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/InMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/InService.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_complete.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_schedule_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/product_progress.jsp
=> 230208 입고처리 완료!

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/OutService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/OutProVO.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/OutSchVo.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/home.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_complete.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_one_of_each_pd.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_process_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_schedule_list.jsp, Team1_Final/src/main/webapp/resources/css/out.css
=> 출고 예정 완료 직전

Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/AccMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_detail.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_modify.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_regist.jsp
=> xml , css // 지수

Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_complete.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_process_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_schedule_list.jsp, Team1_Final/src/main/webapp/resources/css/in.css
=> 230209 입고 처리 품목 코드, 창고 코드 수정

Team1_Final/src/main/java/com/itwillbs/team1_final/svc/InService.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_process_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_update.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp, Team1_Final/src/main/webapp/resources/css/in.css
=> 230209 입고 처리 완료

Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml
=> 2302029 창고 검색 수정

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/webapp/WEB-INF/views/out/out_empSearch.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/temp111.jsp, Team1_Final/src/main/webapp/resources/css/out.css
=> 출고 예정 등록 재작업중

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/AccController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/AccMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/AccService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/AccVO.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/AccMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_detail.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_modify.jsp, Team1_Final/src/main/webapp/WEB-INF/views/acc/acc_regist.jsp
=> css 빼고 다 함 //지수

Team1_Final/src/main/webapp/WEB-INF/views/in/in_complete.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_update.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/product_progress.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/search_product.jsp
주소창에 입력해도 창 안 뜨도록 수정 + 입고 예정 등록할 때 클릭한 자리에 물품 들어가게 수정했어요^0^
=> 230211 권한 수정, 입고 예정 등록 시 클릭한 자리에 물품 들어가게 수정

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/OutController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/OutMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/OutService.java, Team1_Final/src/main/java/com/itwillbs/team1_final/vo/OutSchVo.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/OutMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/out/out_process_update.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_stockSearch.jsp
=> 출고 처리 수정 완료 버전

Team1_Final/src/main/webapp/WEB-INF/views/out/out_accSearch.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_complete.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_empSearch.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_one_of_each_pd.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_pdSearch.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_pdSearch_update.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_process_list.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_process_update.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_regist.jsp, Team1_Final/src/main/webapp/WEB-INF/views/out/out_stockSearch.jsp, Team1_Final/src/main/webapp/resources/css/out.css
=> 권한 부여 및 submit 조건 작성 완료

Team1_Final/src/main/java/com/itwillbs/team1_final/controller/InController.java, Team1_Final/src/main/java/com/itwillbs/team1_final/mapper/InMapper.java, Team1_Final/src/main/java/com/itwillbs/team1_final/svc/InService.java, Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_process.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_product_update.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/product_progress.jsp, Team1_Final/src/main/webapp/WEB-INF/views/in/search_product.jsp
이것저것 많이 수정했어요...
입고 예정 등록할 때 한번에 같은 품목은 등록 할 수 없게 했어요...
그리고 자잘한 오류들도 고쳤습니다...ㅎㅎ
=> 230212 이것저것 많이 수정,,,

Team1_Final/src/main/resources/META-INF/com/itwillbs/team1_final/InMapper.xml, Team1_Final/src/main/webapp/WEB-INF/views/in/in_registration.jsp
=> 230212 view 테이블 수정 + 입고 예정 등록 수정

Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/controller/MemberController.java, Team1_DaengGeul_Spring/src/main/java/com/itwillbs/team1/controller/ProductFrontController.java, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/spring/root-context.xml, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/community/CommunityDetail.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/community/Community_List0.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/community/Community_List1.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/customer/qna_list.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/inc/main.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/inc/main_index.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/inc/memberInfo_left.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_delete.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_delete_result.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_info.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_info_search_form.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_join_form.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_join_result.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_list.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_login_form.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/member/member_search_passwd_result.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/order/cart_form.jsp, Team1_DaengGeul_Spring/src/main/webapp/WEB-INF/views/order/product_detail.jsp, Team1_Final/src/main/webapp/WEB-INF/spring/root-context.xml
23.02.20 RDS로 DB 연동완료 / 댕글 member .me 없앰
=> 23.02.20 RDS로 DB 연동완료 / 댕글 member .me 없앰
